version: "3.4"

services:
  bcoem:
    image: bcoem:php
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:80
    environment:
      BCOEM_SETUP_FREE_ACCESS: "false"
      DB_DATABASE: bcoem
      DB_HOST: db
      DB_PASSWORD: bcoem
      DB_USER: bcoem
  db:
    image: mariadb:10.5
    environment:
      MARIADB_DATABASE: bcoem
      MARIADB_PASSWORD: bcoem
      MARIADB_ROOT_PASSWORD: root-password
      MARIADB_USER: bcoem
