#! /bin/bash -e

echo "BCOE&M docker entrypoint"
echo "========================"

bcoem-configure
bcoem-set-db
bcoem-set-debug
bcoem-set-port
bcoem-set-ssl

echo "========================"
echo "Starting Apache..."

exec /usr/local/bin/apache2-foreground
