#! /bin/bash -e

echo "BCOE&M CONFIGURE"
echo "================"

conf_file=/var/www/html/site/config.php

if [[ "${SETUP_FREE_ACCESS}" == true ]]; then
    echo "Enabling free access"
    sed -ri -e "s/\\\$setup_free_access =  FALSE;/\\\$setup_free_access = TRUE;/g" "$conf_file"
else
    echo "Disabling free access"
    sed -ri -e "s/\\\$setup_free_access =  TRUE;/\\\$setup_free_access = FALSE;/g" "$conf_file"
fi

echo "================"
